### PR TITLE
only test regex pattern if user input not empty

### PR DESCRIPTION
**Pull request by aeldemery**
If the user press enter without input, the regex test fails, so test it only if non default value.

### CODE REVIEW

**Comment by Prince781** [comment]
While it's a little awkward, I think we want the regex to match the default value. If it doesn't, then the template needs to be corrected.

**Comment by aeldemery** [comment]
Ok, now I understand what the problem is. If I put the default value as one of the project variables, it may fail as it's not get substituted.
example:
If I made a variable `${APP_REAL_NAME}` and put the default as `${PROJECT_NAME}` it fails because it test the regex against `${PROJECT_NAME}` . It's also not very convenient as it doesn't display the substituted value to the user. Any idea how to solve this?

**Comment by Prince781** [comment]
@aeldemery usually you'd want to reference a variable to replace it. Therefore, your default should be of the form `/${OTHER_VARIABLE}/<non-empty pattern>/<possibly empty pattern>/`. If you're defining a variable to be exactly another variable, then you just use that variable instead, right?

**Comment by Prince781** [comment]
@aeldemery I pushed some fixes to substitution recently. Maybe it helps with your problem. Let me know how I can help you with making a template.

**Pull request closed without merging**
